name: Linux
on:
  push:
    branches:
        - main
        - f/*
  pull_request:
    branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt update && sudo apt install --quiet -y bash make gcc g++ clang tcc python3 python3-pytest valgrind
      - name: Build and test
        run: |
          ./ut retest
