name: Windows
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: setup msys2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: bash msys/make mingw64/mingw-w64-x86_64-gcc msys/python msys/python-pytest mingw64/mingw-w64-x86_64-clang git cmake

    - name: setup-tcc
      run: |
        bash tools/install_tcc.sh

    - name: Build and test
      shell: msys2 {0}
      run: |
        TCC=tinycc/the_install/tcc.exe ./ut retest
